import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '@/store/AuthContext';

export const metadata: Metadata = {
    title: 'Chat App Professionals',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
